<?xml version="1.0" encoding="utf-8"?>
<Database Name="JinxBot" Class="JinxBotDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ROB-TABLET\SQLEXPRESS;Initial Catalog=JinxBot;Integrated Security=True" SettingsObjectName="JinxBot.Data.LinqToSqlClient.Properties.Settings" SettingsPropertyName="JinxBotConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ClientSessions" Member="ClientSessions">
    <Type Name="ClientSession">
      <Column Name="ClientSessionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Client" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Server" Type="System.String" DbType="VarChar(127) NOT NULL" CanBeNull="false" />
      <Column Name="VersionFile1" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="VersionFile2" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="VersionFile3" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="VersionFile4" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Started" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Ended" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ClientSession_SessionPacket" Member="SessionPackets" OtherKey="SessionID" Type="SessionPacket" />
    </Type>
  </Table>
  <Table Name="dbo.SessionPackets" Member="SessionPackets">
    <Type Name="SessionPacket">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SessionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Contents" Type="System.Data.Linq.Binary" DbType="VarBinary(2048) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="ClientSession_SessionPacket" Member="ClientSession" ThisKey="SessionID" Type="ClientSession" IsForeignKey="true" />
    </Type>
  </Table>
</Database>