//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BNSharp.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account &apos;{0}&apos; does not exist.  Attempting to create....
        /// </summary>
        internal static string AccountDNECreating {
            get {
                return ResourceManager.GetString("AccountDNECreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.net specified an invalid packet size..
        /// </summary>
        internal static string InvalidPacketSizeFromBnet {
            get {
                return ResourceManager.GetString("InvalidPacketSizeFromBnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username and/or password..
        /// </summary>
        internal static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server rejected your password..
        /// </summary>
        internal static string LoginProofClientProofFailed {
            get {
                return ResourceManager.GetString("LoginProofClientProofFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server rejected your password with a specific error message: &apos;{0}&apos;.
        /// </summary>
        internal static string LoginProofCustomError {
            get {
                return ResourceManager.GetString("LoginProofCustomError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon success!  Battle.net has requested that you register an e-mail address with this account.  You will not be notified again..
        /// </summary>
        internal static string LoginProofRegisterEmail {
            get {
                return ResourceManager.GetString("LoginProofRegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server was unable to verify that it knew your password; you may be connecting to a malicious server..
        /// </summary>
        internal static string LoginProofServerProofFailed {
            get {
                return ResourceManager.GetString("LoginProofServerProofFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon success!  Entering chat....
        /// </summary>
        internal static string LoginProofSuccess {
            get {
                return ResourceManager.GetString("LoginProofSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user name contained too few alphanumeric characters..
        /// </summary>
        internal static string NameCreateFail10 {
            get {
                return ResourceManager.GetString("NameCreateFail10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user name contained too many adjacent punctuation characters..
        /// </summary>
        internal static string NameCreateFail11 {
            get {
                return ResourceManager.GetString("NameCreateFail11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user name contained too many punctuation characters..
        /// </summary>
        internal static string NameCreateFail12 {
            get {
                return ResourceManager.GetString("NameCreateFail12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user name was too short or blank.  User names should be at least 3 characters long..
        /// </summary>
        internal static string NameCreateFail7 {
            get {
                return ResourceManager.GetString("NameCreateFail7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user name contained one or more illegal characters..
        /// </summary>
        internal static string NameCreateFail8 {
            get {
                return ResourceManager.GetString("NameCreateFail8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user name contained one or more illegal words..
        /// </summary>
        internal static string NameCreateFail9 {
            get {
                return ResourceManager.GetString("NameCreateFail9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user name already exists..
        /// </summary>
        internal static string NameCreateFailOther {
            get {
                return ResourceManager.GetString("NameCreateFailOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created account name &apos;{0}&apos;.  Logging in....
        /// </summary>
        internal static string NameCreateSuccess {
            get {
                return ResourceManager.GetString("NameCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat client.
        /// </summary>
        internal static string ProdCHAT {
            get {
                return ResourceManager.GetString("ProdCHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diablo II (Retail).
        /// </summary>
        internal static string ProdD2DV {
            get {
                return ResourceManager.GetString("ProdD2DV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diablo 2: Shareware.
        /// </summary>
        internal static string ProdD2SH {
            get {
                return ResourceManager.GetString("ProdD2SH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diablo II: The Lord of Destruction.
        /// </summary>
        internal static string ProdD2XP {
            get {
                return ResourceManager.GetString("ProdD2XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan Starcraft.
        /// </summary>
        internal static string ProdJSTR {
            get {
                return ResourceManager.GetString("ProdJSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starcraft: Brood War.
        /// </summary>
        internal static string ProdSEXP {
            get {
                return ResourceManager.GetString("ProdSEXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starcraft: Shareware.
        /// </summary>
        internal static string ProdSSHR {
            get {
                return ResourceManager.GetString("ProdSSHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starcraft (Retail).
        /// </summary>
        internal static string ProdSTAR {
            get {
                return ResourceManager.GetString("ProdSTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Unknown Product or Client.
        /// </summary>
        internal static string ProdUNKN {
            get {
                return ResourceManager.GetString("ProdUNKN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warcraft II: Battle.net Edition.
        /// </summary>
        internal static string ProdW2BN {
            get {
                return ResourceManager.GetString("ProdW2BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warcraft III: The Frozen Throne.
        /// </summary>
        internal static string ProdW3XP {
            get {
                return ResourceManager.GetString("ProdW3XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warcraft III: The Reign of Chaos.
        /// </summary>
        internal static string ProdWAR3 {
            get {
                return ResourceManager.GetString("ProdWAR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.net has sent a packet that exceeds the maximum length supported..
        /// </summary>
        internal static string ReceivedTooLongMessage {
            get {
                return ResourceManager.GetString("ReceivedTooLongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection was unable to complete a connection to {0}:{1} (&apos;{2}&apos;).  More information is available in the exception..
        /// </summary>
        internal static string UnableToConnectFmt {
            get {
                return ResourceManager.GetString("UnableToConnectFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your computer was unable to resolve host name &apos;{0}&apos;.  If necessary, add an entry to %SystemRoot%\system32\drivers\etc\hosts, or flush your DNS resolver cache, and try again..
        /// </summary>
        internal static string UnableToResolveHostFmt {
            get {
                return ResourceManager.GetString("UnableToResolveHostFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.net has requested that your account be upgraded, but this is not supported.  Please upgrade your account via the official Warcraft III client..
        /// </summary>
        internal static string UpgradeRequestedUnsupported {
            get {
                return ResourceManager.GetString("UpgradeRequestedUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Warcraft 3 server validation check failed.  You may not be connecting to a legitimate Battle.net server..
        /// </summary>
        internal static string War3ServerValidationFailed {
            get {
                return ResourceManager.GetString("War3ServerValidationFailed", resourceCulture);
            }
        }
    }
}
